# Generated by Django 3.0.3 on 2020-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200303_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='asset',
            field=models.CharField(default='', max_length=50),
        ),
    ]
