# Generated by Django 3.0.3 on 2020-03-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_room_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chat_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='room_x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='room_y_position',
            field=models.IntegerField(default=0),
        ),
    ]
